version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.16
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "bookstoredb"
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - jsf-bookstore-network
  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8081:8080
    networks:
      - jsf-bookstore-network

networks:
  jsf-bookstore-network:
    driver: bridge
